/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 doom.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function Model(props: GroupProps) {
  const { nodes, materials } = useGLTF("/doom.glb") as any;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.l1.geometry} material={materials.l1} />
      <mesh geometry={nodes.l2.geometry} material={materials.l2} />
      <mesh geometry={nodes.m0.geometry} material={materials.m0} />
      <mesh geometry={nodes.m1.geometry} material={materials.m1} />
      <mesh geometry={nodes.m2.geometry} material={materials.m2} />
      <mesh
        geometry={nodes.m3.geometry}
        material={materials.m3}
        position={[-0.217, 0, 0]}
      />
      <mesh
        geometry={nodes.m4.geometry}
        material={materials.m4}
        position={[-0.217, 0, 0]}
      />
      <mesh
        geometry={nodes.m5.geometry}
        material={materials.m5}
        position={[-0.217, 0, 0]}
      />
      <mesh
        geometry={nodes.m6.geometry}
        material={materials.m6}
        position={[-0.217, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/doom.glb");
